### ISSUE TITLE
NotImplementedError: Exception encountered when calling Lambda.call().

### ISSUE THREAD

**Issue by Aya-Balbaa** [mikelkou/fava#17]
Hi there, 

Thank you so much for this package.

I am having this error when using fava.cook. 
We could not automatically infer the shape of the Lambda's output. Please specify the `output_shape` argument for this Lambda layer.

Arguments received by Lambda.call():
  • args=(['<KerasTensor shape=(None, 100), dtype=float32, sparse=False, name=keras_tensor_20>', '<KerasTensor shape=(None, 100), dtype=float32, sparse=False, name=keras_tensor_21>'],)
  • kwargs={'mask': ['None', 'None']}

I have also tried using adata, and got this error.

  return self.nnz != 0
    395 else:
--> 396     raise ValueError("The truth value of an array with more than one "
    397                      "element is ambiguous. Use a.any() or a.all().")

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all().
adata

any suggestions to solve that please?

Many thanks,
Aya

**Comment by mikelkou** [comment]
Hi, thank you for reaching out. I haven't encountered this error but  I will look into it and come back to you asap. 
Just make sure that you have installed the latest `fava` version, as I have made some changed with the cut-off.

Best,
Mikaela

**Comment by mikelkou** [comment]
Due to some recent updates on Anndata, you might have the issue with the sparse version of anndata.X.

Could you please try using this code:
```
adata.X = adata.X.toarray()
adata.var.index.name = None
fava.cook(data=adata, epochs=epochs, hidden_layer = hidden_layer, latent_dim = latent_dim, interaction_count=interaction_count)
```

I am planning to update the code. However, regarding the other issue, I need more context. I haven't encountered this before.

**Comment by Aya-Balbaa** [comment]
Thank you for your response.

converting adata.X to array worked and now it's giving the same error as when using the tab delimited matrix.
Could this be related to Tensorflow version?
These are the versions in my env


tensorboard               2.16.2                   pypi_0    pypi
tensorboard-data-server   0.7.2                    pypi_0    pypi
tensorflow                2.16.1                   pypi_0    pypi
tensorflow-io-gcs-filesystem 0.36.0                   pypi_0    pypi

CUDA Version: 2.16.1

**This is the whole error:**

---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
Cell In[34], line 1
----> 1 my_FAVAourite_network = fava.cook(
      2     data=t_df,
      3     log2_normalization=False,  # If your data are normalized set this to False
      4     hidden_layer=100,  # If None, it will be adjusted base on the input size.
      5     latent_dim=None,  # If None, it will be adjusted base on the size of the hidden layer.
      6     epochs=50,
      7     batch_size=32,
      8     CC_cutoff=0.95,
      9 )  # This is arbitraty. We need to plot the score distribution.
     10 my_FAVAourite_network

File /path/to/fava/lib/python3.10/site-packages/favapy/fava.py:385, in cook(data, log2_normalization, hidden_layer, latent_dim, epochs, batch_size, interaction_count, correlation_type, CC_cutoff)
    383 opt = tf.keras.optimizers.Adam(learning_rate=0.001, clipnorm=0.001)
    384 x_train = x_test = np.array(x)
--> 385 vae = VAE(
    386     opt, x_train, x_test, batch_size, original_dim, hidden_layer, latent_dim, epochs
    387 )
    388 x_test_encoded = np.array(vae.encoder.predict(x_test, batch_size=batch_size))
    389 correlation = create_protein_pairs(x_test_encoded, row_names, correlation_type)

File //path/to/fava/lib/python3.10/site-packages/favapy/fava.py:192, in VAE.__init__(self, opt, x_train, x_test, batch_size, original_dim, hidden_layer, latent_dim, epochs)
    187     epsilon = K.random_normal(
    188         shape=(K.shape(z_mean)[0], latent_dim), mean=0.0, stddev=0.1
    189     )
    190     return z_mean + K.exp(z_log_sigma) * epsilon
--> 192 z = layers.Lambda(sampling)([z_mean, z_log_sigma])
    194 # Create encoder
    195 encoder = keras.Model(inputs, [z_mean, z_log_sigma, z], name="encoder")

File /path/to/fava/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py:122, in filter_traceback.<locals>.error_handler(*args, **kwargs)
    119     filtered_tb = _process_traceback_frames(e.__traceback__)
    120     # To get the full stack trace, call:
    121     # `keras.config.disable_traceback_filtering()`
--> 122     raise e.with_traceback(filtered_tb) from None
    123 finally:
    124     del filtered_tb

File /path/to/site-packages/keras/src/layers/core/lambda_layer.py:95, in Lambda.compute_output_shape(self, input_shape)
     93         return tree.map_structure(lambda x: x.shape, output_spec)
     94     except:
---> 95         raise NotImplementedError(
     96             "We could not automatically infer the shape of "
     97             "the Lambda's output. Please specify the `output_shape` "
     98             "argument for this Lambda layer."
     99         )
    101 if callable(self._output_shape):
    102     return self._output_shape(input_shape)

NotImplementedError: Exception encountered when calling Lambda.call().

We could not automatically infer the shape of the Lambda's output. Please specify the `output_shape` argument for this Lambda layer.

Arguments received by Lambda.call():
  • args=(['<KerasTensor shape=(None, 5), dtype=float32, sparse=False, name=keras_tensor_26>', '<KerasTensor shape=(None, 5), dtype=float32, sparse=False, name=keras_tensor_27>'],)
  • kwargs={'mask': ['None', 'None']}

Thank you

**Comment by Aya-Balbaa** [comment]
@mikelkou any suggestions please.
I am keen on using this tool :)

**Comment by mikelkou** [comment]
Give me few days to check on this and update the package. It seems like I need to update the keras layer.
I will come back to you asap. Thanks for reporting and let me know if anything changes.

**Comment by Aya-Balbaa** [comment]
@mikelkou  any updates please?

**Comment by mikelkou** [comment]
Hi @Aya-Balbaa,

Thanks for checking in. I have updated the code and the problem should be solved now. You also don't need to transform your anndata prior to fava, as I integrated that as well. 

Try to install the new release (v1.0.1). Let me know if it works for you. I will leave the issue open for now.

**Comment by mikelkou** [comment]
Hi @Aya-Balbaa,

I am closing the issue now as it seems it is solved. Feel free to open a new one if you have more questions.
