### ISSUE TITLE
”ValueError: A KerasTensor cannot be used as input to a TensorFlow function “ in fava.cook function 

### ISSUE THREAD

**Issue by CGAfresh** [mikelkou/fava#20]
Dear favapy's contributors,
**I run the code according to the** [tutorial](https://fava.readthedocs.io/en/main/tutorials/How_to_use_favapy_in_a_notebook.html#The-input-in-this-case-should-be-a-tab-separated-matrix-with-observations-as-columns-and-variables-as-rows.-In-other-words,-in-the-rows-should-be-the-entities-that-will-be-the-nodes-of-our-network.) 
**And I installed the latest version [v1.0.1]，but I encountered the following errors**:
# !pip install favapy==0.3.9.4
from favapy import fava
data = pd.read_csv("data/Example_dataset_GSE75748_sc_cell_type_ec.tsv", sep="\t")
my_FAVAourite_network = fava.cook(
    data=data,
    log2_normalization=False,  # If your data are normalized set this to False
    hidden_layer=None,  # If None, it will be adjusted base on the input size.
    latent_dim=None,  # If None, it will be adjusted base on the size of the hidden layer.
    epochs=50,
    batch_size=32, 
    CC_cutoff = 0.95
)  # This is arbitraty. We need to plot the score distribution.
my_FAVAourite_network
Traceback (most recent call last):

  Cell In[9], line 1
    my_FAVAourite_network = fava.cook(

  File I:\python packages\envs\kkkk\Lib\site-packages\favapy\fava.py:454 in cook
    vae = VAE(

  File I:\python packages\envs\kkkk\Lib\site-packages\favapy\fava.py:198 in __init__
    reconstruction_loss = keras.losses.mean_squared_error(inputs, outputs)

  File I:\python packages\envs\kkkk\Lib\site-packages\keras\src\losses\losses.py:1300 in mean_squared_error
    y_pred = ops.convert_to_tensor(y_pred)

  File I:\python packages\envs\kkkk\Lib\site-packages\keras\src\ops\core.py:917 in convert_to_tensor
    return backend.convert_to_tensor(x, dtype=dtype, sparse=sparse)

  File I:\python packages\envs\kkkk\Lib\site-packages\keras\src\backend\tensorflow\core.py:125 in convert_to_tensor
    return tf.convert_to_tensor(x, dtype=dtype)

  File I:\python packages\envs\kkkk\Lib\site-packages\tensorflow\python\util\traceback_utils.py:153 in error_handler
    raise e.with_traceback(filtered_tb) from None

  File I:\python packages\envs\kkkk\Lib\site-packages\keras\src\backend\common\keras_tensor.py:138 in __tf_tensor__
    raise ValueError(

ValueError: A KerasTensor cannot be used as input to a TensorFlow function. A KerasTensor is a symbolic placeholder for a shape and dtype, used when constructing Keras Functional models or Keras Functions. You can only use it as input to a Keras layer or a Keras operation (from the namespaces `keras.layers` and `keras.operations`). You are likely doing something like:
```
x = Input(...)
...
tf_fn(x)  # Invalid.
```
What you should do instead is wrap `tf_fn` in a layer:
```
class MyLayer(Layer):
    def call(self, x):
        return tf_fn(x)
x = MyLayer()(x)
```
**How to solve it？**

**Comment by CGAfresh** [comment]
this is my env list:
Package                       Version
----------------------------- ------------
absl-py                       2.1.0
alabaster                     0.7.16
anndata                       0.10.9
anyio                         4.2.0
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
array_api_compat              1.9.1
arrow                         1.3.0
astroid                       2.14.2
asttokens                     2.0.5
astunparse                    1.6.3
async-lru                     2.0.4
atomicwrites                  1.4.0
attrs                         23.1.0
autopep8                      2.0.4
Babel                         2.11.0
bcrypt                        3.2.0
beautifulsoup4                4.12.2
binaryornot                   0.4.4
black                         24.8.0
bleach                        4.1.0
Brotli                        1.0.9
certifi                       2024.8.30
cffi                          1.16.0
chardet                       4.0.0
charset-normalizer            2.0.4
click                         8.1.7
cloudpickle                   3.0.0
colorama                      0.4.6
comm                          0.1.2
contourpy                     1.3.0
cookiecutter                  2.6.0
cryptography                  43.0.0
cycler                        0.12.1
debugpy                       1.6.7
decorator                     5.1.1
defusedxml                    0.7.1
Deprecated                    1.2.14
diff-match-patch              20200713
dill                          0.3.8
docstring-to-markdown         0.11
docutils                      0.18.1
executing                     0.8.3
fastjsonschema                2.16.2
favapy                        1.0.1
flake8                        7.0.0
flatbuffers                   24.3.25
fonttools                     4.54.1
future                        1.0.0
gast                          0.6.0
google-pasta                  0.2.0
graphtools                    1.5.3
grpcio                        1.67.1
h5py                          3.12.1
idna                          3.4
imagesize                     1.4.1
importlib-metadata            7.0.1
inflection                    0.5.1
intervaltree                  3.1.0
ipykernel                     6.28.0
ipython                       8.20.0
isort                         5.13.2
jaraco.classes                3.2.1
jedi                          0.18.1
jellyfish                     1.0.1
Jinja2                        3.1.3
joblib                        1.4.2
json5                         0.9.6
jsonschema                    4.19.2
jsonschema-specifications     2023.7.1
jupyter_client                8.6.0
jupyter_core                  5.5.0
jupyter-events                0.8.0
jupyter-lsp                   2.2.0
jupyter_server                2.10.0
jupyter_server_terminals      0.4.4
jupyterlab                    4.0.11
jupyterlab-pygments           0.1.2
jupyterlab_server             2.25.1
keras                         3.6.0
keyring                       24.3.1
kiwisolver                    1.4.7
lazy-object-proxy             1.10.0
libclang                      18.1.1
magic-impute                  3.0.0
Markdown                      3.7
markdown-it-py                2.2.0
MarkupSafe                    2.1.3
matplotlib                    3.9.2
matplotlib-inline             0.1.6
mccabe                        0.7.0
mdurl                         0.1.0
mistune                       2.0.4
ml-dtypes                     0.4.1
more-itertools                10.3.0
mypy-extensions               1.0.0
namex                         0.0.8
natsort                       8.4.0
nbclient                      0.8.0
nbconvert                     7.10.0
nbformat                      5.9.2
nest-asyncio                  1.6.0
notebook                      7.0.8
notebook_shim                 0.2.3
numpy                         1.26.4
numpydoc                      1.7.0
opt_einsum                    3.4.0
optree                        0.13.0
overrides                     7.4.0
packaging                     23.1
pandas                        2.0.0
pandocfilters                 1.5.0
paramiko                      2.8.1
parso                         0.8.3
pathspec                      0.10.3
pexpect                       4.8.0
pickleshare                   0.7.5
pillow                        11.0.0
pip                           23.3.1
platformdirs                  3.10.0
pluggy                        1.0.0
ply                           3.11
prometheus-client             0.14.1
prompt-toolkit                3.0.43
protobuf                      5.28.3
psutil                        5.9.0
ptyprocess                    0.7.0
pure-eval                     0.2.2
pycodestyle                   2.11.1
pycparser                     2.21
pydocstyle                    6.3.0
pyflakes                      3.2.0
Pygments                      2.15.1
PyGSP                         0.5.1
pylint                        2.16.2
pylint-venv                   3.0.3
pyls-spyder                   0.4.0
PyNaCl                        1.5.0
pyparsing                     3.2.0
PyQt5                         5.15.10
PyQt5-sip                     12.13.0
PyQtWebEngine                 5.15.6
PySocks                       1.7.1
python-dateutil               2.8.2
python-json-logger            2.0.7
python-lsp-black              2.0.0
python-lsp-jsonrpc            1.1.2
python-lsp-server             1.10.0
python-slugify                5.0.2
pytoolconfig                  1.2.6
pytz                          2023.3.post1
pywin32                       305.1
pywin32-ctypes                0.2.2
pywinpty                      2.0.10
PyYAML                        6.0.1
pyzmq                         25.1.2
QDarkStyle                    3.2.3
qstylizer                     0.2.2
QtAwesome                     1.3.1
qtconsole                     5.5.1
QtPy                          2.4.1
referencing                   0.30.2
requests                      2.31.0
rfc3339-validator             0.1.4
rfc3986-validator             0.1.1
rich                          13.7.1
rope                          1.12.0
rpds-py                       0.10.6
Rtree                         1.0.1
scikit-learn                  1.5.2
scipy                         1.14.1
scprep                        1.2.3
Send2Trash                    1.8.2
setuptools                    68.2.2
sip                           6.7.12
six                           1.16.0
sniffio                       1.3.0
snowballstemmer               2.2.0
sortedcontainers              2.4.0
soupsieve                     2.5
Sphinx                        7.3.7
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.10
spyder                        5.5.1
spyder-kernels                2.5.0
stack-data                    0.2.0
tabulate                      0.9.0
tasklogger                    1.2.0
tensorboard                   2.18.0
tensorboard-data-server       0.7.2
tensorflow                    2.18.0
tensorflow_intel              2.18.0
tensorflow-io-gcs-filesystem  0.31.0
termcolor                     2.5.0
terminado                     0.17.1
text-unidecode                1.3
textdistance                  4.2.1
threadpoolctl                 3.5.0
three-merge                   0.1.1
tinycss2                      1.2.1
tomli                         2.0.1
tomlkit                       0.13.2
tornado                       6.3.3
traitlets                     5.7.1
typing_extensions             4.9.0
tzdata                        2024.2
ujson                         5.10.0
Unidecode                     1.3.8
urllib3                       2.1.0
watchdog                      4.0.1
wcwidth                       0.2.5
webencodings                  0.5.1
websocket-client              0.58.0
Werkzeug                      3.1.1
whatthepatch                  1.0.2
wheel                         0.41.2
win-inet-pton                 1.1.0
wrapt                         1.14.1
yapf                          0.40.2
zipp                          3.20.2

**Comment by CGAfresh** [comment]
ok，I have found the solution for this problem which was caused by the version of tensorflow. 
I downgraded the version of tensorflow to 2.13.1 and this code no longer gives errors：pip install tensorflow==2.13.1；
Hope it can help others.

**Comment by mikelkou** [comment]
Hello,

sorry for not responding faster and thanks for giving the answer here. I hope everything works now but let me know if there are any more issues.

**Comment by Rohit-Satyam** [comment]
@CGAfresh cam you please tell which python version did you use?

**Comment by CGAfresh** [comment]
> @CGAfresh cam you please tell which python version did you use?
my env is Python 3.11.8
